<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>05_为什么要用Promise</title>
</head>
<body>

<script>
  /* 
  优势：
    1. 指定回调函数的方式更加灵活: 
      旧的: 必须在启动异步任务前指定
      promise: 启动异步任务 => 返回promie对象 => 给promise对象绑定回调函数(甚至可以在异步任务结束后指定)

    2. 支持链式调用, 可以解决回调地狱问题
      什么是回调地狱? 回调函数嵌套调用, 外部回调函数异步执行的结果是嵌套的回调函数执行的条件
      回调地狱的缺点?  不便于阅读 / 不便于异常处理
      一个不是很优秀的解决方案? promise链式调用
      终极解决方案? async/await（底层实际上依然使用then的链式调用）
    */

  //1.纯回调函数形式处理异步任务
  /*$.ajax({
    url:'http://localhost:3000/demo2',
    method:'POST',
    data:{name:'会开车的老刘',age:18},
    success:(result)=>{
      $.ajax({
        url:'http://localhost:3000/demo2',
        method:'POST',
        data:{name:'会开车的老刘',age:18},
        success:(result)=>{
          $.ajax({
            url:'http://localhost:3000/demo2',
            method:'POST',
            data:{name:'会开车的老刘',age:18},
            success:(result)=>{console.log(result)}, //请求成功的回调
            error:(err)=>{console.log(err)} //请求失败的回调
          })
        }, //请求成功的回调
        error:(err)=>{console.log(err)} //请求失败的回调
      })
    }, //请求成功的回调
    error:(err)=>{console.log(err)} //请求失败的回调
  })*/

  //2.使用Promise处理异步任务(借助了then的链式调用)
  /*let p1 = new Promise((resolve,reject)=>{
    console.log('开始了第1次请求')
    $.get('https://api.apiopen.top/videoCategory',(data)=>{
      resolve(data)
    })
  })
  p1.then(
    value => {
      console.log('第1次请求成功了，数据:',value)
      return new Promise((resolve,reject)=>{
        console.log('开始了第2次请求')
        $.get('https://api.apiopen.top/todayVideo',(data)=>{
          resolve(data)
        })
      })
    },
    reason => {console.log(reason)}
  )
    .then(
      value => {
        console.log('第2次请求成功了，数据:',value)
        return new Promise((resolve,reject)=>{
          console.log('开始了第3次请求')
          $.get('https://api.apiopen.top/videoCategory',(data)=>{
            resolve(data)
          })
        })
      },
      reason => {console.log(reason)},
    )
    .then(
      value => {
        console.log('第3次请求成功了，数据:',value)
      },
      reason => {console.log(reason)},
    )*/

  //3.Promise配合async/await: 回调地狱的终极解决方案(伪代码,主要看结构)
  /*async function request() {
    try {
      const result = await doSomething()
      const newResult = await doSomethingElse(result)
      const finalResult = await doThirdThing(newResult)
      console.log('Got the final result: ' + finalResult)
    } catch (error) {
      failureCallback(error)
    }
  }*/

</script>
</body>
</html>